<?xml version="1.0" encoding="utf-8"?><Database Name="InventarioAnkhalDB" Class="InventarioAnkhalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Bases" Member="Bases">
    <Type Name="Bases">
      <Column Name="BaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MetaTarimasDia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaCajasDia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaAccesoriosDia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UsuarioAltaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bases_Entregas" Member="Entregas" ThisKey="BaseID" OtherKey="BaseOrigenID" Type="Entregas" />
      <Association Name="Bases_Movimientos" Member="Movimientos" ThisKey="BaseID" OtherKey="BaseDestinoID" Type="Movimientos" />
      <Association Name="Bases_Movimientos1" Member="Movimientos1" ThisKey="BaseID" OtherKey="BaseOrigenID" Type="Movimientos" />
      <Association Name="Bases_Produccion" Member="Produccion" ThisKey="BaseID" OtherKey="BaseID" Type="Produccion" />
      <Association Name="Bases_StockMateriales" Member="StockMateriales" ThisKey="BaseID" OtherKey="BaseID" Type="StockMateriales" />
      <Association Name="Bases_StockProductos" Member="StockProductos" ThisKey="BaseID" OtherKey="BaseID" Type="StockProductos" />
      <Association Name="Usuarios_Bases" Member="Usuarios" ThisKey="UsuarioAltaID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConsumosProduccion" Member="ConsumosProduccion">
    <Type Name="ConsumosProduccion">
      <Column Name="ConsumoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProduccionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadReal" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadTeoricaMin" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadTeoricaMax" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="EsMerma" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Notas" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Materiales_ConsumosProduccion" Member="Materiales" ThisKey="MaterialID" OtherKey="MaterialID" Type="Materiales" IsForeignKey="true" />
      <Association Name="Produccion_ConsumosProduccion" Member="Produccion" ThisKey="ProduccionID" OtherKey="ProduccionID" Type="Produccion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetalleEntregas" Member="DetalleEntregas">
    <Type Name="DetalleEntregas">
      <Column Name="DetalleEntregaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntregaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoItem" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaqueteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Entregas_DetalleEntregas" Member="Entregas" ThisKey="EntregaID" OtherKey="EntregaID" Type="Entregas" IsForeignKey="true" />
      <Association Name="Paquetes_DetalleEntregas" Member="Paquetes" ThisKey="PaqueteID" OtherKey="PaqueteID" Type="Paquetes" IsForeignKey="true" />
      <Association Name="Productos_DetalleEntregas" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Entregas" Member="Entregas">
    <Type Name="Entregas">
      <Column Name="EntregaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Folio" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BaseOrigenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RegistradoPorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Entregas_DetalleEntregas" Member="DetalleEntregas" ThisKey="EntregaID" OtherKey="EntregaID" Type="DetalleEntregas" />
      <Association Name="Entregas_Movimientos" Member="Movimientos" ThisKey="EntregaID" OtherKey="EntregaID" Type="Movimientos" />
      <Association Name="Bases_Entregas" Member="Bases" ThisKey="BaseOrigenID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Usuarios_Entregas" Member="Usuarios" ThisKey="RegistradoPorID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materiales" Member="Materiales">
    <Type Name="Materiales">
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TipoMaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subtipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Unidad" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="StockMinimo" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="StockOptimo" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UsuarioAltaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Materiales_ConsumosProduccion" Member="ConsumosProduccion" ThisKey="MaterialID" OtherKey="MaterialID" Type="ConsumosProduccion" />
      <Association Name="Materiales_Movimientos" Member="Movimientos" ThisKey="MaterialID" OtherKey="MaterialID" Type="Movimientos" />
      <Association Name="Materiales_PaqueteComponentes" Member="PaqueteComponentes" ThisKey="MaterialID" OtherKey="MaterialID" Type="PaqueteComponentes" />
      <Association Name="Materiales_ProductoMateriales" Member="ProductoMateriales" ThisKey="MaterialID" OtherKey="MaterialID" Type="ProductoMateriales" />
      <Association Name="Materiales_StockMateriales" Member="StockMateriales" ThisKey="MaterialID" OtherKey="MaterialID" Type="StockMateriales" />
      <Association Name="TiposMaterial_Materiales" Member="TiposMaterial" ThisKey="TipoMaterialID" OtherKey="TipoMaterialID" Type="TiposMaterial" IsForeignKey="true" />
      <Association Name="Usuarios_Materiales" Member="Usuarios" ThisKey="UsuarioAltaID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movimientos" Member="Movimientos">
    <Type Name="Movimientos">
      <Column Name="MovimientoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoMovimientoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoItem" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseOrigenID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseDestinoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="Costo" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="EntregaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProduccionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RegistradoPorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaMovimiento" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Bases_Movimientos" Member="Bases" ThisKey="BaseDestinoID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Bases_Movimientos1" Member="Bases1" ThisKey="BaseOrigenID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Entregas_Movimientos" Member="Entregas" ThisKey="EntregaID" OtherKey="EntregaID" Type="Entregas" IsForeignKey="true" />
      <Association Name="Materiales_Movimientos" Member="Materiales" ThisKey="MaterialID" OtherKey="MaterialID" Type="Materiales" IsForeignKey="true" />
      <Association Name="Produccion_Movimientos" Member="Produccion" ThisKey="ProduccionID" OtherKey="ProduccionID" Type="Produccion" IsForeignKey="true" />
      <Association Name="Productos_Movimientos" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
      <Association Name="TiposMovimiento_Movimientos" Member="TiposMovimiento" ThisKey="TipoMovimientoID" OtherKey="TipoMovimientoID" Type="TiposMovimiento" IsForeignKey="true" />
      <Association Name="Usuarios_Movimientos" Member="Usuarios" ThisKey="RegistradoPorID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaqueteComponentes" Member="PaqueteComponentes">
    <Type Name="PaqueteComponentes">
      <Column Name="PaqueteComponenteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaqueteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoComponente" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioUnitario" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Association Name="Materiales_PaqueteComponentes" Member="Materiales" ThisKey="MaterialID" OtherKey="MaterialID" Type="Materiales" IsForeignKey="true" />
      <Association Name="Paquetes_PaqueteComponentes" Member="Paquetes" ThisKey="PaqueteID" OtherKey="PaqueteID" Type="Paquetes" IsForeignKey="true" />
      <Association Name="Productos_PaqueteComponentes" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paquetes" Member="Paquetes">
    <Type Name="Paquetes">
      <Column Name="PaqueteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UsuarioAltaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Paquetes_DetalleEntregas" Member="DetalleEntregas" ThisKey="PaqueteID" OtherKey="PaqueteID" Type="DetalleEntregas" />
      <Association Name="Paquetes_PaqueteComponentes" Member="PaqueteComponentes" ThisKey="PaqueteID" OtherKey="PaqueteID" Type="PaqueteComponentes" />
      <Association Name="Usuarios_Paquetes" Member="Usuarios" ThisKey="UsuarioAltaID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Produccion" Member="Produccion">
    <Type Name="Produccion">
      <Column Name="ProduccionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Turno" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadBuena" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRechazo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaDia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RegistradoPorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Produccion_ConsumosProduccion" Member="ConsumosProduccion" ThisKey="ProduccionID" OtherKey="ProduccionID" Type="ConsumosProduccion" />
      <Association Name="Produccion_Movimientos" Member="Movimientos" ThisKey="ProduccionID" OtherKey="ProduccionID" Type="Movimientos" />
      <Association Name="Bases_Produccion" Member="Bases" ThisKey="BaseID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Productos_Produccion" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
      <Association Name="Usuarios_Produccion" Member="Usuarios" ThisKey="RegistradoPorID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoMateriales" Member="ProductoMateriales">
    <Type Name="ProductoMateriales">
      <Column Name="ProductoMaterialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadMin" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadMax" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="Notas" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Materiales_ProductoMateriales" Member="Materiales" ThisKey="MaterialID" OtherKey="MaterialID" Type="Materiales" IsForeignKey="true" />
      <Association Name="Productos_ProductoMateriales" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Productos" Member="Productos">
    <Type Name="Productos">
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TipoProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UsuarioAltaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Productos_DetalleEntregas" Member="DetalleEntregas" ThisKey="ProductoID" OtherKey="ProductoID" Type="DetalleEntregas" />
      <Association Name="Productos_Movimientos" Member="Movimientos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Movimientos" />
      <Association Name="Productos_PaqueteComponentes" Member="PaqueteComponentes" ThisKey="ProductoID" OtherKey="ProductoID" Type="PaqueteComponentes" />
      <Association Name="Productos_Produccion" Member="Produccion" ThisKey="ProductoID" OtherKey="ProductoID" Type="Produccion" />
      <Association Name="Productos_ProductoMateriales" Member="ProductoMateriales" ThisKey="ProductoID" OtherKey="ProductoID" Type="ProductoMateriales" />
      <Association Name="Productos_StockProductos" Member="StockProductos" ThisKey="ProductoID" OtherKey="ProductoID" Type="StockProductos" />
      <Association Name="TiposProducto_Productos" Member="TiposProducto" ThisKey="TipoProductoID" OtherKey="TipoProductoID" Type="TiposProducto" IsForeignKey="true" />
      <Association Name="Usuarios_Productos" Member="Usuarios" ThisKey="UsuarioAltaID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="RolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Roles_UsuarioRoles" Member="UsuarioRoles" ThisKey="RolID" OtherKey="RolID" Type="UsuarioRoles" />
    </Type>
  </Table>
  <Table Name="dbo.StockMateriales" Member="StockMateriales">
    <Type Name="StockMateriales">
      <Column Name="StockMaterialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadActual" Type="System.Decimal" DbType="Decimal(12,4) NOT NULL" CanBeNull="false" />
      <Column Name="FechaUltimaModif" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Bases_StockMateriales" Member="Bases" ThisKey="BaseID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Materiales_StockMateriales" Member="Materiales" ThisKey="MaterialID" OtherKey="MaterialID" Type="Materiales" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StockProductos" Member="StockProductos">
    <Type Name="StockProductos">
      <Column Name="StockProductoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadBuenas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRechazo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaUltimaModif" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Bases_StockProductos" Member="Bases" ThisKey="BaseID" OtherKey="BaseID" Type="Bases" IsForeignKey="true" />
      <Association Name="Productos_StockProductos" Member="Productos" ThisKey="ProductoID" OtherKey="ProductoID" Type="Productos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TiposMaterial" Member="TiposMaterial">
    <Type Name="TiposMaterial">
      <Column Name="TipoMaterialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TiposMaterial_Materiales" Member="Materiales" ThisKey="TipoMaterialID" OtherKey="TipoMaterialID" Type="Materiales" />
    </Type>
  </Table>
  <Table Name="dbo.TiposMovimiento" Member="TiposMovimiento">
    <Type Name="TiposMovimiento">
      <Column Name="TipoMovimientoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AfectaStock" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TiposMovimiento_Movimientos" Member="Movimientos" ThisKey="TipoMovimientoID" OtherKey="TipoMovimientoID" Type="Movimientos" />
    </Type>
  </Table>
  <Table Name="dbo.TiposProducto" Member="TiposProducto">
    <Type Name="TiposProducto">
      <Column Name="TipoProductoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TiposProducto_Productos" Member="Productos" ThisKey="TipoProductoID" OtherKey="TipoProductoID" Type="Productos" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioRoles" Member="UsuarioRoles">
    <Type Name="UsuarioRoles">
      <Column Name="UsuarioRolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaAsignacion" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaRevocacion" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="AsignadoPorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Roles_UsuarioRoles" Member="Roles" ThisKey="RolID" OtherKey="RolID" Type="Roles" IsForeignKey="true" />
      <Association Name="Usuarios_UsuarioRoles" Member="Usuarios" ThisKey="AsignadoPorID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
      <Association Name="Usuarios_UsuarioRoles1" Member="Usuarios1" ThisKey="UsuarioID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoPaterno" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ApellidoMaterno" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NombreFamiliar" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TelefonoFamiliar" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UltimoAcceso" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="FechaModif" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="UsuarioAltaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Usuarios_Bases" Member="Bases" ThisKey="UsuarioID" OtherKey="UsuarioAltaID" Type="Bases" />
      <Association Name="Usuarios_Entregas" Member="Entregas" ThisKey="UsuarioID" OtherKey="RegistradoPorID" Type="Entregas" />
      <Association Name="Usuarios_Materiales" Member="Materiales" ThisKey="UsuarioID" OtherKey="UsuarioAltaID" Type="Materiales" />
      <Association Name="Usuarios_Movimientos" Member="Movimientos" ThisKey="UsuarioID" OtherKey="RegistradoPorID" Type="Movimientos" />
      <Association Name="Usuarios_Paquetes" Member="Paquetes" ThisKey="UsuarioID" OtherKey="UsuarioAltaID" Type="Paquetes" />
      <Association Name="Usuarios_Produccion" Member="Produccion" ThisKey="UsuarioID" OtherKey="RegistradoPorID" Type="Produccion" />
      <Association Name="Usuarios_Productos" Member="Productos" ThisKey="UsuarioID" OtherKey="UsuarioAltaID" Type="Productos" />
      <Association Name="Usuarios_UsuarioRoles" Member="UsuarioRoles" ThisKey="UsuarioID" OtherKey="AsignadoPorID" Type="UsuarioRoles" />
      <Association Name="Usuarios_UsuarioRoles1" Member="UsuarioRoles1" ThisKey="UsuarioID" OtherKey="UsuarioID" Type="UsuarioRoles" />
      <Association Name="Usuarios_Usuarios" Member="Usuarios2" ThisKey="UsuarioID" OtherKey="UsuarioAltaID" Type="Usuarios" />
      <Association Name="Usuarios_Usuarios" Member="Usuarios1" ThisKey="UsuarioAltaID" OtherKey="UsuarioID" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
</Database>