//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{

    public partial class Entregas
    {

        // ── Dashboard ──────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Label lblTotalHoy;
        protected global::System.Web.UI.WebControls.Label lblProgramadas;
        protected global::System.Web.UI.WebControls.Label lblEntregadas;
        protected global::System.Web.UI.WebControls.Label lblCanceladas;
        protected global::System.Web.UI.WebControls.Label lblValorTotal;

        // ── Filtros ────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrBase;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrEstado;
        protected global::System.Web.UI.WebControls.TextBox      txtFiltrCliente;
        protected global::System.Web.UI.WebControls.TextBox      txtFiltrFolio;
        protected global::System.Web.UI.WebControls.TextBox      txtFiltrDesde;
        protected global::System.Web.UI.WebControls.TextBox      txtFiltrHasta;
        protected global::System.Web.UI.WebControls.Button       btnBuscar;
        protected global::System.Web.UI.WebControls.Button       btnLimpiar;

        // ── Acciones ───────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button    btnNuevo;
        protected global::System.Web.UI.WebControls.Label     lblResultados;

        // ── Grid ───────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.GridView  gvEntregas;

        // ── Hidden fields ──────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.HiddenField hdnMensajePendiente;
        protected global::System.Web.UI.WebControls.HiddenField hdnItemsJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnAccion;
        protected global::System.Web.UI.WebControls.HiddenField hdnEntregaIDAccion;
        protected global::System.Web.UI.WebControls.HiddenField hdnDetalleJson;

        // ── Botón de acción oculto ─────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button    btnProcesarAccion;

        // ── Modal Nueva Entrega ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox      txtNuevoFolio;
        protected global::System.Web.UI.WebControls.TextBox      txtNuevoFecha;
        protected global::System.Web.UI.WebControls.DropDownList ddlNuevoBase;
        protected global::System.Web.UI.WebControls.DropDownList ddlNuevoCliente;
        protected global::System.Web.UI.WebControls.TextBox      txtNuevoObservaciones;

        // Selectores de item en el modal
        protected global::System.Web.UI.WebControls.DropDownList ddlItemProducto;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemMaterial;

        // Botones del modal
        protected global::System.Web.UI.WebControls.Button btnGuardarProgramada;
        protected global::System.Web.UI.WebControls.Button btnConfirmarEntregar;
    }
}
