//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{
    public partial class InventarioPorBase
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnMensajePendiente;

        protected global::System.Web.UI.WebControls.DropDownList ddlBase;

        protected global::System.Web.UI.WebControls.DropDownList ddlTipoItem;

        protected global::System.Web.UI.WebControls.TextBox txtBuscarMateriales;

        protected global::System.Web.UI.WebControls.TextBox txtBuscarProductos;

        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        protected global::System.Web.UI.WebControls.Button btnExportarExcel;

        protected global::System.Web.UI.WebControls.Button btnExportarPdf;

        protected global::System.Web.UI.WebControls.Panel pnlMateriales;

        protected global::System.Web.UI.WebControls.Label lblTotalMateriales;

        protected global::System.Web.UI.WebControls.GridView gvMateriales;

        protected global::System.Web.UI.WebControls.Panel pnlProductos;

        protected global::System.Web.UI.WebControls.Label lblTotalProductos;

        protected global::System.Web.UI.WebControls.GridView gvProductos;
    }
}
