//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{
    public partial class Inventario
    {
        /// <summary>
        /// hdnMensajePendiente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMensajePendiente;

        /// <summary>
        /// lblValorTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValorTotal;

        /// <summary>
        /// lblValorMateriales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValorMateriales;

        /// <summary>
        /// lblValorBuenos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValorBuenos;

        /// <summary>
        /// lblValorRechazo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValorRechazo;

        /// <summary>
        /// ddlBase control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBase;

        /// <summary>
        /// ddlTipoItem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoItem;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// btnLimpiar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// btnExportarExcel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportarExcel;

        /// <summary>
        /// btnExportarPdf control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportarPdf;

        /// <summary>
        /// pnlMateriales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMateriales;

        /// <summary>
        /// lblTotalMateriales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalMateriales;

        /// <summary>
        /// gvMateriales control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvMateriales;

        /// <summary>
        /// pnlProductos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProductos;

        /// <summary>
        /// lblTotalProductos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalProductos;

        /// <summary>
        /// gvProductos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProductos;

        /// <summary>
        /// pnlResumen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResumen;

        /// <summary>
        /// gvResumen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvResumen;
    }
}
