//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario {

    public partial class Mermas {

        protected global::System.Web.UI.WebControls.Label lblTotalEntradas;

        protected global::System.Web.UI.WebControls.Label lblValorMerma;

        protected global::System.Web.UI.WebControls.Button btnNuevaConversion;

        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrBase;

        protected global::System.Web.UI.WebControls.TextBox txtFiltrMaterial;

        protected global::System.Web.UI.WebControls.Button btnBuscar;

        protected global::System.Web.UI.WebControls.Button btnLimpiarFiltros;

        protected global::System.Web.UI.WebControls.Label lblResultados;

        protected global::System.Web.UI.WebControls.GridView gvMermas;

        protected global::System.Web.UI.WebControls.GridView gvHistorial;

        protected global::System.Web.UI.WebControls.HiddenField hdnMensajePendiente;

        protected global::System.Web.UI.WebControls.HiddenField hdnOutputsJson;

        protected global::System.Web.UI.WebControls.DropDownList ddlConvBase;

        protected global::System.Web.UI.WebControls.HiddenField hdnConvMatOrigenID;

        protected global::System.Web.UI.WebControls.TextBox txtConvCantOrigen;

        protected global::System.Web.UI.WebControls.TextBox txtConvObs;

        protected global::System.Web.UI.WebControls.Button btnGuardarConversion;

        protected global::System.Web.UI.WebControls.HiddenField hdnOrigenUnidadVal;

        protected global::System.Web.UI.WebControls.HiddenField hdnOrigenFactor;
    }
}
