//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{
    public partial class MetasProduccion
    {
        /// <summary>Control lblMetaTotal.</summary>
        protected global::System.Web.UI.WebControls.Label lblMetaTotal;

        /// <summary>Control lblCardMeta.</summary>
        protected global::System.Web.UI.WebControls.Label lblCardMeta;

        /// <summary>Control lblCumplimiento.</summary>
        protected global::System.Web.UI.WebControls.Label lblCumplimiento;

        /// <summary>Control txtDesde.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesde;

        /// <summary>Control txtHasta.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtHasta;

        /// <summary>Control btnBuscar.</summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>Control btnLimpiar.</summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>Control lblPeriodo.</summary>
        protected global::System.Web.UI.WebControls.Label lblPeriodo;

        /// <summary>Control lblNumDias.</summary>
        protected global::System.Web.UI.WebControls.Label lblNumDias;

        /// <summary>Control rptMetaBases.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptMetaBases;
    }
}
