// -----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost.
// </auto-generated>
// -----------------------------------------------------------------------

namespace GrupoAnkhalInventario
{
    public partial class Ordenes
    {
        protected global::System.Web.UI.WebControls.Label                lblTotal;
        protected global::System.Web.UI.WebControls.Label                lblAbiertas;
        protected global::System.Web.UI.WebControls.Label                lblParciales;
        protected global::System.Web.UI.WebControls.Label                lblCompletadas;
        protected global::System.Web.UI.WebControls.Label                lblCanceladas;
        protected global::System.Web.UI.WebControls.Label                lblValorTotal;
        protected global::System.Web.UI.WebControls.DropDownList         ddlFiltrBase;
        protected global::System.Web.UI.WebControls.DropDownList         ddlFiltrEstado;
        protected global::System.Web.UI.WebControls.TextBox              txtFiltrCliente;
        protected global::System.Web.UI.WebControls.TextBox              txtFiltrFolio;
        protected global::System.Web.UI.WebControls.TextBox              txtFiltrDesde;
        protected global::System.Web.UI.WebControls.TextBox              txtFiltrHasta;
        protected global::System.Web.UI.WebControls.Button               btnBuscar;
        protected global::System.Web.UI.WebControls.Button               btnLimpiar;
        protected global::System.Web.UI.WebControls.Button               btnNuevoOrden;
        protected global::System.Web.UI.WebControls.Label                lblResultados;
        protected global::System.Web.UI.WebControls.GridView             gvOrdenes;
        protected global::System.Web.UI.WebControls.HiddenField          hdnMensajePendiente;
        protected global::System.Web.UI.WebControls.HiddenField          hdnOrdenIDAccion;
        protected global::System.Web.UI.WebControls.HiddenField          hdnAccion;
        protected global::System.Web.UI.WebControls.HiddenField          hdnItemsJson;
        protected global::System.Web.UI.WebControls.HiddenField          hdnDetalleJson;
        protected global::System.Web.UI.WebControls.HiddenField          hdnPartidaJson;
        protected global::System.Web.UI.WebControls.HiddenField          hdnEntregaItemsJson;
        protected global::System.Web.UI.WebControls.HiddenField          hdnEntregaIDAccion;
        protected global::System.Web.UI.WebControls.HiddenField          hdnModoGuardado;
        protected global::System.Web.UI.WebControls.HiddenField          hdnNumeroFactura;
        protected global::System.Web.UI.WebControls.HiddenField          hdnFechaEntregaConf;
        protected global::System.Web.UI.WebControls.Button               btnProcesarAccion;
        protected global::System.Web.UI.WebControls.Button               btnGuardarPartida;
        protected global::System.Web.UI.WebControls.TextBox              txtNuevoFolio;
        protected global::System.Web.UI.WebControls.TextBox              txtNuevoFecha;
        protected global::System.Web.UI.WebControls.DropDownList         ddlNuevoBase;
        protected global::System.Web.UI.WebControls.DropDownList         ddlNuevoCliente;
        protected global::System.Web.UI.WebControls.TextBox              txtNuevoObservaciones;
        protected global::System.Web.UI.WebControls.Button               btnGuardarOrden;
        protected global::System.Web.UI.WebControls.TextBox              txtPartidaFecha;
        protected global::System.Web.UI.WebControls.TextBox              txtPartidaFactura;
        protected global::System.Web.UI.WebControls.TextBox              txtPartidaObs;
    }
}
