//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por herramienta.
//
//     Los cambios en este archivo podrian causar un comportamiento incorrecto y se perderan si
//     se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{


    public partial class Produccion
    {

        /// <summary>
        /// Control lblRegistrosHoy.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRegistrosHoy;

        /// <summary>
        /// Control lblUnidadesBuenas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUnidadesBuenas;

        /// <summary>
        /// Control lblUnidadesRechazo.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUnidadesRechazo;

        /// <summary>
        /// Control btnNuevo.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>
        /// Control ddlFiltrBase.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrBase;

        /// <summary>
        /// Control ddlFiltrProducto.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrProducto;

        /// <summary>
        /// Control ddlFiltrTurno.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltrTurno;

        /// <summary>
        /// Control txtFechaDesde.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;

        /// <summary>
        /// Control txtFechaHasta.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;

        /// <summary>
        /// Control btnBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// Control btnLimpiar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// Control lblResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultados;

        /// <summary>
        /// Control gvProduccion.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProduccion;

        /// <summary>
        /// Control hdnMensajePendiente.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMensajePendiente;

        /// <summary>
        /// Control hdnConsumosJson.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnConsumosJson;

        /// <summary>
        /// Control ddlBase.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBase;

        /// <summary>
        /// Control txtFecha.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFecha;

        /// <summary>
        /// Control ddlTurno.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTurno;

        /// <summary>
        /// Control ddlProducto.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;

        /// <summary>
        /// Control txtCantidadBuena.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadBuena;

        /// <summary>
        /// Control txtCantidadRechazo.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCantidadRechazo;

        /// <summary>
        /// Control txtObservaciones.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;

        /// <summary>
        /// Control btnGuardar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// Control litJsData.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litJsData;
    }
}
