//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{
    public partial class RegistrarProveedores
    {
        // ── Filtros ────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtBuscar;
        protected global::System.Web.UI.WebControls.DropDownList  ddlFiltrEstado;
        protected global::System.Web.UI.WebControls.Button        btnBuscar;
        protected global::System.Web.UI.WebControls.Button        btnLimpiarFiltros;

        // ── Acciones ───────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button        btnNuevo;
        protected global::System.Web.UI.WebControls.Label         lblResultados;

        // ── Grid ───────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.GridView      gvProveedores;

        // ── Hidden fields ──────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.HiddenField   hdnToggleProveedorID;
        protected global::System.Web.UI.WebControls.HiddenField   hdnMensajePendiente;
        protected global::System.Web.UI.WebControls.HiddenField   hdnProveedorID;

        // ── Botón toggle oculto ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button        btnToggleHidden;

        // ── Modal Nuevo — Tab Generales ────────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList  ddlTipoPersona;
        protected global::System.Web.UI.WebControls.TextBox       txtNombre;
        protected global::System.Web.UI.WebControls.TextBox       txtContacto;
        protected global::System.Web.UI.WebControls.TextBox       txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox       txtEmail;
        protected global::System.Web.UI.WebControls.TextBox       txtPaginaWeb;
        protected global::System.Web.UI.WebControls.DropDownList  ddlTipoEmpresa;
        protected global::System.Web.UI.WebControls.TextBox       txtNacionalidad;

        // ── Modal Nuevo — Tab Fiscal ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtRazonSocialFiscal;
        protected global::System.Web.UI.WebControls.TextBox       txtRFC;
        protected global::System.Web.UI.WebControls.DropDownList  ddlRegimenFiscal;
        protected global::System.Web.UI.WebControls.TextBox       txtCURP;

        // ── Modal Nuevo — Tab Bancario ─────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtBanco;
        protected global::System.Web.UI.WebControls.TextBox       txtCLABE;
        protected global::System.Web.UI.WebControls.TextBox       txtCuentaBancaria;
        protected global::System.Web.UI.WebControls.TextBox       txtTitularCuenta;
        protected global::System.Web.UI.WebControls.TextBox       txtDiasCredito;
        protected global::System.Web.UI.WebControls.TextBox       txtLimiteCredito;

        // ── Modal Nuevo — Tab Dirección ────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtPais;
        protected global::System.Web.UI.WebControls.TextBox       txtCodigoPostal;
        protected global::System.Web.UI.WebControls.TextBox       txtEstado;
        protected global::System.Web.UI.WebControls.TextBox       txtMunicipio;
        protected global::System.Web.UI.WebControls.TextBox       txtColonia;
        protected global::System.Web.UI.WebControls.TextBox       txtNumExt;
        protected global::System.Web.UI.WebControls.TextBox       txtNumInt;
        protected global::System.Web.UI.WebControls.TextBox       txtReferencia;
        protected global::System.Web.UI.WebControls.Button        btnGuardar;

        // ── Modal Editar — Tab Generales ───────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList  ddlTipoPersonaEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtNombreEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtContactoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtTelefonoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtEmailEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtPaginaWebEdit;
        protected global::System.Web.UI.WebControls.DropDownList  ddlTipoEmpresaEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtNacionalidadEdit;

        // ── Modal Editar — Tab Fiscal ──────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtRazonSocialFiscalEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtRFCEdit;
        protected global::System.Web.UI.WebControls.DropDownList  ddlRegimenFiscalEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtCURPEdit;

        // ── Modal Editar — Tab Bancario ────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtBancoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtCLABEEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtCuentaBancariaEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtTitularCuentaEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtDiasCreditoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtLimiteCreditoEdit;

        // ── Modal Editar — Tab Dirección ───────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtPaisEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtCodigoPostalEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtEstadoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtMunicipioEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtColoniaEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtNumExtEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtNumIntEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtReferenciaEdit;
        protected global::System.Web.UI.WebControls.Button        btnGuardarEdit;

        // ── Modal Materiales — HiddenFields y botones servidor ─────────────────
        protected global::System.Web.UI.WebControls.HiddenField   hdnMaterialesProveedorID;
        protected global::System.Web.UI.WebControls.HiddenField   hdnProveedorMaterialID;
        protected global::System.Web.UI.WebControls.HiddenField   hdnAccionMateriales;
        protected global::System.Web.UI.WebControls.HiddenField   hdnNuevoPrecio;
        protected global::System.Web.UI.WebControls.HiddenField   hdnNuevaNotaPrecio;
        protected global::System.Web.UI.WebControls.Button        btnGuardarProveedorMaterial;
        protected global::System.Web.UI.WebControls.Button        btnActualizarPrecio;
        protected global::System.Web.UI.WebControls.Button        btnAccionMateriales;

        // ── Modal Materiales — Controles del modal ─────────────────────────────
        protected global::System.Web.UI.WebControls.Label         lblProveedorNombreMat;
        protected global::System.Web.UI.WebControls.DropDownList  ddlMaterialAgregar;
        protected global::System.Web.UI.WebControls.TextBox       txtPrecioAgregar;
        protected global::System.Web.UI.WebControls.GridView      gvMaterialesProveedor;
        protected global::System.Web.UI.WebControls.GridView      gvHistorial;
        protected global::System.Web.UI.WebControls.Label         lblHistorialMaterial;
    }
}
