//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoAnkhalInventario
{

    public partial class RegistrarClientes
    {
        // ── Filtros ────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtBuscar;
        protected global::System.Web.UI.WebControls.DropDownList  ddlFiltrEstado;
        protected global::System.Web.UI.WebControls.Button        btnBuscar;
        protected global::System.Web.UI.WebControls.Button        btnLimpiarFiltros;

        // ── Acciones ───────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button        btnNuevo;
        protected global::System.Web.UI.WebControls.Label         lblResultados;

        // ── Grid ───────────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.GridView      gvClientes;

        // ── Hidden fields ──────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.HiddenField   hdnToggleClienteID;
        protected global::System.Web.UI.WebControls.HiddenField   hdnMensajePendiente;
        protected global::System.Web.UI.WebControls.HiddenField   hdnClienteID;

        // ── Botón toggle oculto ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button        btnToggleHidden;

        // ── Modal Nuevo Cliente ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtNombre;
        protected global::System.Web.UI.WebControls.TextBox       txtContacto;
        protected global::System.Web.UI.WebControls.TextBox       txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox       txtEmail;
        protected global::System.Web.UI.WebControls.TextBox       txtDireccion;
        protected global::System.Web.UI.WebControls.Button        btnGuardar;

        // ── Modal Editar Cliente ───────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox       txtNombreEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtContactoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtTelefonoEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtEmailEdit;
        protected global::System.Web.UI.WebControls.TextBox       txtDireccionEdit;
        protected global::System.Web.UI.WebControls.Button        btnGuardarEdit;
    }
}
